use sistema_parqueos;

CREATE TABLE USUARIOS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    email VARCHAR(191) NOT NULL UNIQUE,
    telefono VARCHAR(20) NOT NULL,
    contrasena VARCHAR(255) NOT NULL,
    role ENUM('admin', 'usuario') NOT NULL DEFAULT 'usuario',
    estado ENUM('activo', 'inactivo') NOT NULL DEFAULT 'activo',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE VEHICULOS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    usuario_id INT NOT NULL REFERENCES usuarios(id),
    placa VARCHAR(20) NOT NULL UNIQUE,
    marca VARCHAR(80),
    modelo VARCHAR(80),
    color VARCHAR(80),
    tipo ENUM('carro', 'motocicleta') NOT NULL DEFAULT 'carro',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE TICKETS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    vehiculo_id INT NOT NULL REFERENCES vehiculos(id),
    fecha_hora_entrada DATETIME NOT NULL,
    fecha_hora_salida DATETIME,
    total_pagar DECIMAL(10, 2) NOT NULL DEFAULT 0,
    status_de_pago ENUM('pendiente', 'pagado') NOT NULL DEFAULT 'pendiente',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE NOTIFICACIONES (
    id INT AUTO_INCREMENT PRIMARY KEY,
    usuario_id INT NOT NULL REFERENCES usuarios(id),
    mensaje TEXT NOT NULL,
    tipo ENUM('emergencia', 'info', 'error') NOT NULL DEFAULT 'info',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE CAMBIOS_PUESTOS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    usuario_id INT NOT NULL REFERENCES usuarios(id),
    espacio_id INT NOT NULL REFERENCES espacios_parqueo(id),
    fecha_de_entrada DATETIME NOT NULL,
    fecha_de_salida DATETIME,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE AUDIT_LOGS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    usuario_id INT NOT NULL REFERENCES usuarios(id),
    accion VARCHAR(255) NOT NULL,
    detalle TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE ESPACIOS_PARQUEO (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    espacio_total INT NOT NULL,
    tiempo_abierto INT NOT NULL,
    tiempo_cerrado INT NOT NULL,
);

CREATE TABLE ESPACIOS_DISPONIBLES (
    id INT AUTO_INCREMENT PRIMARY KEY,
    espacio_id INT NOT NULL REFERENCES espacios_parqueo(id),
    disponible BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE RESERVACIONES (
    id INT AUTO_INCREMENT PRIMARY KEY,
    usuario_id INT NOT NULL REFERENCES usuarios(id),
    espacio_id INT NOT NULL REFERENCES espacios_parqueo(id),
    fecha_de_entrada DATETIME NOT NULL,
    fecha_de_salida DATETIME,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE SECCIONES_PARQUEO (
    id INT AUTO_INCREMENT PRIMARY KEY,
    vehiculo_id INT NOT NULL REFERENCES vehiculos(id),
    espacio_id INT NOT NULL REFERENCES espacios_parqueo(id),
    estado ENUM('disponible', 'ocupado') NOT NULL DEFAULT 'disponible',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE PAGOS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    usuario_id INT NOT NULL REFERENCES usuarios(id),
    ticket_id INT NOT NULL REFERENCES tickets(id),
    monto DECIMAL(10, 2) NOT NULL,
    fecha_de_pago DATETIME NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE RATES (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    descripcion TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);